language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
install:
  - cat /proc/meminfo
  - cat /proc/cpuinfo
  - dpkg --get-selections
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh